### ISSUE TITLE
Ancient Warfare Research doesn't work

### ISSUE THREAD

**Issue by CosmoTheCosmicCat** [HostileNetworks/ReignModpack#14]
When attempting to research, I have the book in the right slot, linked to me, with the research selected and the proper materials in it, but the research won't progress. Either I'm missing something or it is a bug.

**Comment by cosmicdan** [comment]
It's working fine for us. Screenshot?

On Jan 22, 2017, CosmoTheCosmicCat <notifications@github.com> wrote:
>When attempting to research, I have the book in the right slot, linked
>to me, with the research selected and the proper materials in it, but
>the research won't progress. Either I'm missing something or it is a
>bug.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by CosmoTheCosmicCat** [comment]
It appears I am a derp and used rye instead of wheat

**Comment by cosmicdan** [comment]
Oh it's Emaps lol. All good :)

On Jan 23, 2017, CosmoTheCosmicCat <notifications@github.com> wrote:
>Closed #14.

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.
